var car = 'subaru';
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car == 'Honda'? I predict false.");
console.log(car == 'Honda');
console.log("Is car == 'Toyota'? I predict false.");
console.log(car == 'Toyata');
console.log(" Is car !== 'Ferrari'? I predict true");
console.log(car !== 'Ferrari');
console.log("Is car !== 'Lancer'? I predict true.");
console.log(car !== 'Lancer');
var age = 25;
console.log(" Is age > 18? I predict true.");
console.log(age > 18);
console.log("Is age < 15? I predict false.");
console.log(age < 15);
